version: "3.9"
services:
  personal_site:
      container_name: personal_site
      image: custom-node-alpine
      networks:
        - homelab
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.personal_site.rule=Host(`personal.issamounejjar.live`)"
        - "traefik.http.routers.personal_site.entrypoints=websecure"
        - "traefik.http.routers.personal_site.tls.certresolver=letsencrypt"
      restart: unless-stopped

networks:
  homelab:
    external: true
